### PR TITLE
Update version.rb

### PR DESCRIPTION
**Pull request by jdoconnor**
update the version so that the gemspec with the set versions can be uploaded to rubygems

### CODE REVIEW

**Comment by jdoconnor** [comment]
@darbyfrey

**Comment by darbyfrey** [comment]
:ship: :it:

**Comment by jdoconnor** [comment]
you know i can't merge this, right? I'll deploy it, but i can't merge :crying_cat_face:

**Comment by darbyfrey** [comment]
Do you now work here anymore? :)

**Comment by jdoconnor** [comment]
merci

**Pull request merged**
