### PR TITLE
Don't pin dependency versions

### PR DESCRIPTION
**Pull request by darbyfrey**
For discussion:

Instead of pinning all these dependencies in the gemspec we should allow them to be pinned by the service instead. I think this will help with the different upgrade conflicts we run into. We may need to pin some version in the next round of service upgrades, but I think this makes more sense from the perspective of the framework. Thoughts?

@bellycard/platform @danielmackey @alexmamonchik @ochagata @jay3dec

### CODE REVIEW

**Comment by shaqq** [comment]
we might consider pinning `thor`, just because the CLI will depend on it. in general, though, i agree

**Comment by ochagata** [comment]
Does it depend on a specific version of thor? @shaqq

**Comment by shaqq** [comment]
@ochagata it could if thor introduces breaking changes

**Comment by ochagata** [comment]
Any other dependencies that might cause it to start failing? @shaqq

**Comment by danielmackey** [comment]
@shaqq @darbyfrey could you get away with a [pessimistic version constraint](http://guides.rubygems.org/patterns/#pessimistic_version_constraint) for thor?

I'd say that active record and grape are probably other libraries that could introduce breaking changes. if they are following semantic versioning, you could constrain to the x.x instead of x.x.x?

**Comment by ochagata** [comment]
As long as the dependency isn't crucial(thor, roar), it should be fine.
Also, I agree with using the pessimistic version constraint for core gems.

**Comment by ashtonthomas** [comment]
Here is a related PR specifically for roar: https://github.com/bellycard/napa/pull/242

**Pull request closed without merging**
