### PR TITLE
WIP: update grape, ruby, roar gems

### PR DESCRIPTION
**Pull request by jdoconnor**
fails tests related to acts_as_fu. Not sure why. any ideas?

### CODE REVIEW

**Comment by shaqq** [comment]
Should the upgrades to grape, ruby, roar, and activerecord be separate PR's?

That way we can version bump and such in a more responsible fashion. And, we can debug this spec failure easier :partly_sunny:

**Comment by jdoconnor** [comment]
Only if you want to have different versions. The author (this guy) should do it separately to figure out why it is failing.

**Comment by shaqq** [comment]
All of those are potentially breaking changes. I personally prefer version bumps in that case.

**Comment by jdoconnor** [comment]
the issue is activerecord's bump. I agree that they're all breaking changes for applications, but this would likely be a major revision bump, as it is bumping roar a major version

**Comment by jdoconnor** [comment]
the failing tests are in sortable_api. is there a reason why that isn't part of the napa_pagination gem? It seems to fit there better

**Comment by umtrey** [comment]
I'm not keen on moving that now.

**Pull request closed without merging**
